### ISSUE TITLE
Create links to existing legacy Red Hat issues tracker for issues that need to be tracked going forward

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/cdi#479]
There are many open issues under the legacy CDI issues tracker at issues.redhat.com. They can be seen by browsing the following:

https://issues.redhat.com/projects/CDI/issues/CDI-726?filter=allopenissues

We need to triage this list and link to those that should be tracked going forward.

**Comment by manovotn** [comment]
During the meeting we have agreed that we will bulk-close all open CDI issues in the RH JIRA tracker with a comment pointing people to GH issue tracker to recreate the issue here if they think it is still relevant. That way we won't recreate issues needlessly and they will pop up organically as all people that partook in any given JIRA will get email notifications.

I will look into doing that, ideally before this week is over.

**Comment by manovotn** [comment]
I have bulk-closed all JIRAs with a comment pointing people to this issue to saying they should recreate the issue in GH if it is still relevant. FTR 260+ issues were closed.

With that, I think we can close this issue.
