### ISSUE TITLE
remove @ExtensionPriority

### ISSUE THREAD

**Issue by Ladicek** [eclipse-ee4j/cdi#505]
Now that `@Priority` can be used on methods (see https://github.com/eclipse-ee4j/common-annotations-api/pull/87), we should just use that instead of our own `@ExtensionPriority`.

**Comment by manovotn** [comment]
We cannot do this unless there is some release in common annotations so I've dropped a comment asking for me.

**Comment by manovotn** [comment]
@Ladicek turns out I am a little dumber than I thought as I didn't realize CDI is getting Jakarta annotations via interceptors API. This means that even with [the new release](https://repo1.maven.org/maven2/jakarta/annotation/jakarta.annotation-api/2.1.0-B1/) we cannot upgrade unless we, at least temporarily, explicitly declare or override the version of jakarta annotations.

I have sent a PR with this dep upgrade over to interceptors spec - https://github.com/eclipse-ee4j/interceptor-api/pull/88
Though I am not sure we'll get the release.

**Comment by Ladicek** [comment]
I don't see why we couldn't add an exclusion and an explicit dependency.

FWIW, over the years, I have developed some sort of affection to shallow dependency trees. The deeper a dependency tree is, the more pain it will inflict on everyone.
